name: 'my first container action'
description: 'A cloud guru'
author: 'Mohannad Emhemed'
inputs:
  myInputs:
    description: 'greeting to use' 
    required: true
    default: 'Awesome Guru'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
